apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: robertszefler/flask-kub-main:$VERSION
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: api-url
        - name: FLASK_ENV
          # FIXME this is problematic. Changing/removing this var will not
          # result in a restart when running kubectl apply
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
     app: main
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30333
